server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: users_service
          uri: ${FIRST_SERVICE}
          predicates:
            - Path= /api/user/**
        - id: films_service
          uri: ${SECOND_SERVICE}
          predicates:
            - Path= /api/film/**
